// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.21.1
// source: talk.proto

package talk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Talk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Talk) Reset() {
	*x = Talk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_talk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Talk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Talk) ProtoMessage() {}

func (x *Talk) ProtoReflect() protoreflect.Message {
	mi := &file_talk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Talk.ProtoReflect.Descriptor instead.
func (*Talk) Descriptor() ([]byte, []int) {
	return file_talk_proto_rawDescGZIP(), []int{0}
}

func (x *Talk) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_talk_proto protoreflect.FileDescriptor

var file_talk_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x61, 0x6c, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x68,
	0x61, 0x74, 0x22, 0x1a, 0x0a, 0x04, 0x54, 0x61, 0x6c, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x32, 0x33,
	0x0a, 0x0b, 0x54, 0x61, 0x6c, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x24, 0x0a,
	0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x0a, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x54, 0x61, 0x6c, 0x6b, 0x1a, 0x0a, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x54, 0x61, 0x6c,
	0x6b, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x74, 0x61, 0x6c, 0x6b, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_talk_proto_rawDescOnce sync.Once
	file_talk_proto_rawDescData = file_talk_proto_rawDesc
)

func file_talk_proto_rawDescGZIP() []byte {
	file_talk_proto_rawDescOnce.Do(func() {
		file_talk_proto_rawDescData = protoimpl.X.CompressGZIP(file_talk_proto_rawDescData)
	})
	return file_talk_proto_rawDescData
}

var file_talk_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_talk_proto_goTypes = []interface{}{
	(*Talk)(nil), // 0: chat.Talk
}
var file_talk_proto_depIdxs = []int32{
	0, // 0: chat.TalkService.SayHello:input_type -> chat.Talk
	0, // 1: chat.TalkService.SayHello:output_type -> chat.Talk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_talk_proto_init() }
func file_talk_proto_init() {
	if File_talk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_talk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Talk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_talk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_talk_proto_goTypes,
		DependencyIndexes: file_talk_proto_depIdxs,
		MessageInfos:      file_talk_proto_msgTypes,
	}.Build()
	File_talk_proto = out.File
	file_talk_proto_rawDesc = nil
	file_talk_proto_goTypes = nil
	file_talk_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TalkServiceClient is the client API for TalkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TalkServiceClient interface {
	SayHello(ctx context.Context, in *Talk, opts ...grpc.CallOption) (*Talk, error)
}

type talkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTalkServiceClient(cc grpc.ClientConnInterface) TalkServiceClient {
	return &talkServiceClient{cc}
}

func (c *talkServiceClient) SayHello(ctx context.Context, in *Talk, opts ...grpc.CallOption) (*Talk, error) {
	out := new(Talk)
	err := c.cc.Invoke(ctx, "/chat.TalkService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TalkServiceServer is the server API for TalkService service.
type TalkServiceServer interface {
	SayHello(context.Context, *Talk) (*Talk, error)
}

// UnimplementedTalkServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTalkServiceServer struct {
}

func (*UnimplementedTalkServiceServer) SayHello(context.Context, *Talk) (*Talk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterTalkServiceServer(s *grpc.Server, srv TalkServiceServer) {
	s.RegisterService(&_TalkService_serviceDesc, srv)
}

func _TalkService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Talk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.TalkService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkServiceServer).SayHello(ctx, req.(*Talk))
	}
	return interceptor(ctx, in, info, handler)
}

var _TalkService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.TalkService",
	HandlerType: (*TalkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _TalkService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "talk.proto",
}
